Add notification : line-notify
watermelon1024/EEW pull request #8
Opened 2024-07-27 19:04 UTC by kukuxx

2024-07-27 23:24 UTC, a3510377 commented
好了說一下歐~~

2024-07-29 11:34 UTC, watermelon1024 requested changes
麻煩更改一下我於上方的 comments

2024-07-29 11:34 UTC, watermelon1024 commented on notification/linenotify/linenotify.py
> +Line_notify_api = "https://notify-api.line.me/api/notify"
請遵循 PEP8，常量命名使用全大寫

2024-07-29 11:34 UTC, watermelon1024 commented on notification/linenotify/linenotify.py
> +                if response.status != 200:
可以使用 response.ok ，避免非 200 的 2xx status code 被視為錯誤

2024-07-29 12:07 UTC, kukuxx commented
已修改完畢

2024-07-29 12:11 UTC, watermelon1024 approved these changes
LGTM

2024-07-29 12:13 UTC, merged